### ISSUE TITLE
SafeCMS hangs if not already logged in.

### ISSUE THREAD

**Issue by jlpell** [badcodeltd/safecms#10]
In order to make sure that SafeCMS starts up correctly, Peruse must have already been opened and account credentials submitted manually.  If I just startup SafeCMS, it launches Peruse automatically as expected. However, even if I login to Alpha2 at that point and authorize the cms, the cms hangs and will not continue. I have had a similar intermittent issue with the Example Email App before, so this may be related to build environment.

**Comment by BadCodeShane** [comment]
Thanks - this is also a known issue, so I'll close this in favour of https://github.com/badcodeltd/safecms/issues/4
