### ISSUE TITLE
Clicking Back to Home button crashes safe-cms

### ISSUE THREAD

**Issue by JPL1** [badcodeltd/safecms#16]
Templates | Whisper | Preview | Back to Home - blank screen, no console log.

**Comment by BadCodeShane** [comment]
Thanks for this, I'll fix that in 0.0.4. 👍

**Comment by BadCodeShane** [comment]
This is resolved in the following commit:

https://github.com/badcodeltd/safecms/commit/45f0a301b01e808cf9e3b1fe45494388de69a9cf

This will be released as part of version 0.0.4

**Comment by BadCodeShane** [comment]
Version 0.0.4 is now live, closing this issue.
