### ISSUE TITLE
Creating a template and previewing without saving to draft first causes freeze

### ISSUE THREAD

**Issue by JPL1** [badcodeltd/safecms#17]
Also, template is not applied to preview.

**Comment by BadCodeShane** [comment]
This is resolved in this commit: https://github.com/badcodeltd/safecms/commit/2021436a26e9da8a4e0efc3ad1568bbf083e470b

And will be released in a hotfix version release 0.0.5, due for release within the next hour.

**Comment by BadCodeShane** [comment]
Version 0.0.5 has been released: https://github.com/badcodeltd/safecms/releases/tag/0.0.5

Closing this issue, thanks @JPL1
