### ISSUE TITLE
Nice to have - ability to toggle between medium editor and html editor

### ISSUE THREAD

**Issue by JPL1** [badcodeltd/safecms#22]
Not sure how feasible that is but it would be nice.

**Comment by BadCodeShane** [comment]
@JPL1 unfortunately, this can't be supported at the moment, the Medium editor isn't capable of taking in arbitrary HTML so things will break. Right now, once you switch from Medium to HTML, that process is irreversible, I can look at implementing a custom editor in the future which allows this, though - for now I'm going to close this.
