### ISSUE TITLE
Cannot post to second domain.

### ISSUE THREAD

**Issue by jlpell** [badcodeltd/safecms#8]
I have been able to create multiple domains and services for each domain without error on Ubuntu 'Artful'. I have also successfully created a hello world post on the first domain service that was created. When trying to submit a post to a second domain service, the cms says everything is fine, but there is an "NFS Error: File not found" in both the browser and peruse when requesting the site.  On both the non-working sites, and the original working site, I have set the "Post URL" to "index.html".

**Comment by BadCodeShane** [comment]
Was the second domain (or service) one that was created with the web hosting manager or the Safe-CMS? This _may_ be a known issue (https://github.com/badcodeltd/safecms/issues/6), but I want to be sure first.

**Comment by jlpell** [comment]
No, this is a fresh account, all actions performed with the account have been via SafeCMS, and SafeCMS is the only authorized application. Each domain request cost 2 PUTs. Already existing domains accurately erred out in the GUI. The NFS error occurs when requesting the site "ex. safe://pop.culture" from different login accounts too.

**Comment by BadCodeShane** [comment]
Okay, thanks a lot, I'll assign it to me and start working on 👍

**Comment by jlpell** [comment]
Confirmed? Am I the only one with this problem?

**Comment by BadCodeShane** [comment]
@jlpell I believe this may have been fixed as a side effect of resolving this issue: https://github.com/badcodeltd/safecms/issues/1

This will be released in 0.0.4 and I'll test it then, if it's still non-functional, I'll look in to why and try to resolve this for you. 👍

**Comment by BadCodeShane** [comment]
Version 0.0.4 is now live, closing this issue.
